disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2 2006"
logo = "Logo.png"

[params.author]
links = [
    {github = "https://github.com/geeksbsmrt"},
    {linkedin = "https://www.linkedin.com/in/awcrawford/"},
]
name = "Adam Crawford"
image = "profile.jpg"
