# .github/workflows/deploy.yml
name: Build and Deploy Hugo Site with Blowfish (Submodule)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo (Extended Version)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'themes/blowfish/package-lock.json'

      - name: Install Node.js Dependencies for Blowfish Theme
        working-directory: ./themes/blowfish
        run: npm ci

      - name: Build Hugo site with Blowfish
        run: hugo --minify
        env:
          HUGO_ENV: production

      # DEBUGGING STEP: Check if the 'public' directory was created and has content
      - name: Verify Build Output
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing contents of root directory:"
          ls -la
          echo "Checking for 'public' directory:"
          if [ -d "public" ]; then
            echo "'public' directory exists. Listing its contents:"
            ls -la public
          else
            echo "'public' directory NOT FOUND!"
            exit 1 # Fail the workflow if public dir is not found
          fi

      - name: Deploy to Server via Rsync
        uses: easingthemes/ssh-deploy@v5.0.0 # Or check for the latest version
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete" # Rsync arguments
          SOURCE: "public/" # Source directory (relative to GITHUB_WORKSPACE)
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}
