# .github/workflows/deploy.yml
name: Build and Deploy Hugo Site with Blowfish (Submodule)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo (Extended Version)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'themes/blowfish/package-lock.json'

      - name: Install Node.js Dependencies for Blowfish Theme
        working-directory: ./themes/blowfish
        run: npm ci

      - name: Build Hugo site with Blowfish
        run: hugo --minify --panicOnWarning -v # Added --panicOnWarning and verbose -v
        env:
          HUGO_ENV: production

      # DEBUGGING STEP: Check if the 'public' directory was created and has content
      - name: Verify Build Output
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing contents of root directory:"
          ls -la
          echo "Checking for 'public' directory:"
          if [ -d "public" ]; then
            echo "'public' directory exists. Listing its contents:"
            ls -la public
          else
            echo "'public' directory NOT FOUND!"
            exit 1 # Fail the workflow if public dir is not found
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying to TARGET_DIR: ${{ secrets.TARGET_DIR }}"
            # Ensure the target directory exists on the server (rsync can create it if parent exists)
            # However, permissions must be correct on the parent for rsync to create TARGET_DIR
            # A safer approach is to ensure TARGET_DIR is created manually on server with correct permissions first.
            rsync -avz --delete ./public/ ${{ secrets.TARGET_DIR }}/
            echo "Rsync command completed."
