# .github/workflows/deploy.yml
name: Build and Deploy Hugo Site with Blowfish (Submodule)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo (Extended Version)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site with Blowfish
        run: hugo --minify
        env:
          HUGO_ENV: production

      - name: Deploy to Server via Rsync
        run: rsync ${{ github.workspace }}/public/ ${{ secrets.TARGET_DIR }} --delete -avz
